### ISSUE TITLE
Estructura de un paquete GAP

### ISSUE THREAD

**Issue by juniors90** [cesarneyit/FusionA#1]
Hola Cesar. Soy Ferreira, Juan David. Soy de Argentina. A principio de este año presencié una charla virtual tuya en FaMAF-UNC-Argentina. Hasta ese momento no conocía el lenguaje GAP. Me interesó mucho ya que recién he terminado la licenciatura en matemática y tengo las intenciones de seguir estudiando el doctorado.

Te agradezco por haber compartido el link de tu repositorio. Hasta el momento hay algo que no he podido solucionar: he investigado la documentación de GAP, más precisamente en [Structure of a GAP Package](https://www.gap-system.org/Manuals/doc/ref/chap76.html#X8383876782480702) para aprender a desarrollar librarías. Aún no logro entender cómo generar automáticamente el manual de una librería utilizando [AutoDoc](https://gap-packages.github.io/AutoDoc/doc/chap0.html) o [GAPdoc](https://www.gap-system.org/Manuals/pkg/GAPDoc/doc/chap0.html). Sé que hay que utilizar XML pero más que eso no sé. Como ya mensioné, soy muy nuevo en el lenguaje.

En fin, mi idea de este `issue` es comentarte que voy a practicar utilizando el repositorio. Si en algún momento puedo solucionar todo, aprenderé a crear librerías en GAP. Ese es mi objetivo.

Saludos.

Juan David

**Comment by cesarneyit** [comment]
Hola Juan David, 
Muchas gracias por el interes en el código. Yo no se tanto al respecto, y me gustaría aprender hacer paquetes. Alguien que si es experto y le podemos preguntar es Leandro Vendramin https://vendramin.github.io/ Si quiere, por favor deme su correo y le escribo un correo con copia usted preguntándole y vemos que nos contesta. 
Saludos,
César

**Comment by juniors90** [comment]
Hola Cesar. Mí e-mail es juandavid9a0@gmail.com

Saludos.

Juan David.
